In [1]:
import pandas as pd
import plotly         
import plotly.express as px
from dash import Dash, dcc, html
import dash_bootstrap_components as dbc  
import plotly.io as pio
import statsmodels
from dash.dependencies import Input,Output,State

In [2]:
app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

In [3]:
df = pd.read_excel("Salary and Months.xlsx")
df.head()

,Position,Month 1,Month 6,Month 12,Month 18,Month 24,Total Expenditure in two years
0,Manager,27917,111667,195417,251250,279167,865418
1,Video editor,20000,80000,120000,160000,180000,560000
2,Video editor(Interns),5000,20000,30000,40000,45000,140000
3,Contingency team(Video Editing),3000,12000,18000,24000,27000,84000
4,Content designer,20833,104167,145833,187500,229167,687500

In [4]:
df1 = pd.read_excel("CombinedData.xlsx")
df1.head()

,Unnamed: 0,Position,Number of employees,Salary/month/employee,Salary/month,Salary/year/employee,Salary/year,Month 1,Month 6,Month 12,Month 18,Month 24
0,0,Manager,1,27916.67,27916.67,335000,335000,27917,111667,195417,251250,279167
1,1,Video editor,1,20000.00,20000.00,240000,240000,20000,80000,120000,160000,180000
2,2,Video editor(Interns),5,1000.00,5000.00,12000,60000,5000,20000,30000,40000,45000
3,3,Contingency team(Video Editing),3,1000.00,3000.00,12000,36000,3000,12000,18000,24000,27000
4,4,Content designer,1,20833.33,20833.33,250000,250000,20833,104167,145833,187500,229167

In [5]:
barchart1 = px.bar(
    data_frame=df1,
    x="Salary/month",
    y="Number of employees",
    color="Position",              
    opacity=0.8,                  
    orientation="v",             
    barmode='relative',        
    
    text='Number of employees',            
    hover_name='Position',

    labels={"Salary/year":"Salary per year", "Salary/month":"Salary per month"}
)

In [6]:
app.layout = html.Div(
    dbc.Container([
    dbc.Row([
        dbc.Col([
            html.Hr(style={'height': '10px', 'color': 'blue'})
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            html.H1("Team - C (Salary Sheet - Creatives & HR)", 
                    style={'textAlign': 'center', 'font-family': 'Merriweather', 'font-weight': 'bold'})
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Hr(style={'height': '10px', 'color': 'blue'})
        ])
    ]),
    
#  ----------------------------------------------------------------------------------------------------------    
    
    dbc.Row([
        dbc.Col([
            html.H1("Salary Calculator")
        ], width=6)
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Label(['Select Positions'], 
                       style={'font-weight': 'bold', "text-align": "center"}),
            dcc.Dropdown(id='Positions',
                    options=[
                            {'label': 'Manager', 'value': 'Manager'},
                            {'label': 'Video editor', 'value': 'Video editor'},
                            {'label': 'Video editor(Interns)', 'value': 'Video editor(Interns)'},
                            {'label': 'Contingency team(Video Editing)	', 'value': 'Contingency team(Video Editing)	'},
                            {'label': 'Content designer', 'value': 'Content designer'},
                            {'label': 'Content designer(Intern)', 'value': 'Content designer(Intern)'},
                            {'label': 'Contingency team(Content Designing)', 'value': 'Contingency team(Content Designing)'},
                            {'label': 'Content writer', 'value': 'Content writer'},
                            {'label': 'Content writer(Intern)', 'value': 'Content writer(Intern)'},
                            {'label': 'Contingency team(Content writing)', 'value': 'Contingency team(Content writing)'},
                            {'label': 'HR manager', 'value': 'HR manager'},
                            {'label': 'Recruiter', 'value': 'Recruiter'}
                    ],
                    optionHeight=35,                    
                    value='Manager',                  
                    disabled=False,                    
                    multi=False,                       
                    searchable=True,                    
                    search_value='',                    
                    placeholder='Please select...',     
                    clearable=True,                     
                    style={'width':"100%"}),
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Br(),
            html.Label(['Enter the number of Employees : '],
                       style={'font-weight': 'bold', "text-align": "left"}), 
            dcc.Input(id='no_of_emp',type='number',placeholder='',
                          style={'display':'inline-block', 'margin-left':'2px'}),
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Label(['Calculator :'],
                           style={'font-weight': 'bold', "text-align": "center"}),
            html.Br(),

            html.Label(['The Salary Per Month Per Employee is: ']),
            html.Div(id='output_container1', children=[]),
            
            html.Label(['Total Expenditure Per Month is: ']),
            html.Div(id='output_container2', children=[]),
            
            html.Label(['The Salary Per Year Per Employee is: ']),
            html.Div(id='output_container3', children=[]),
            
            html.Label(['Total Expenditure Per Year is: ']),
            html.Div(id='output_container4', children=[]),
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Hr(style={'height': '10px', 'color': 'blue'})
        ])
    ]),
    
#  ----------------------------------------------------------------------------------------------------------
    
    dbc.Row([
        dbc.Col([
            html.H1("Departments Classification")
        ], width=6),
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Label(['Select Department'],
                       style={'font-weight': 'bold', "text-align": "center"}),
            dcc.Dropdown(options=[
                            {'label': 'Creatives', 'value': 'Creatives'},
                            {'label': 'HR', 'value': 'HR'}
            ], 
            value='Creatives', clearable=True, id='Department'),
            html.Br(),
            html.Br()
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            dcc.Graph(id='Graph1')
        ], width=12, align="center")
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Hr(style={'height': '10px', 'color': 'blue'})
        ])
    ]),
    
#  ----------------------------------------------------------------------------------------------------------
     
    dbc.Row([
        dbc.Col([
            html.H1("Expenditure of Ozibook Ltd")
        ], width=6)
    ]),
    
    dbc.Row([
        dbc.Col([
            dcc.Graph(id='Graph2')
        ], width=8),
        
        dbc.Col([
            html.Label(['Y-axis values to compare:'], 
                       style={'font-weight': 'bold'}),
            dcc.Dropdown(
                id='yaxis_raditem',
                options=[
                         {'label': 'Month 1', 'value': 'Month 1'},
                         {'label': 'Month 6', 'value': 'Month 6'},
                         {'label': 'Month 12', 'value': 'Month 12'},
                         {'label': 'Month 18', 'value': 'Month 18'},
                         {'label': 'Month 24', 'value': 'Month 24'},
                         {'label': 'Total Expenditure in Two years', 'value': 'Total Expenditure in two years'}
                ],
                optionHeight=35,                    
                    value='Month 1',                  
                    disabled=False,                    
                    multi=False,                       
                    searchable=True,                    
                    search_value='',                    
                    placeholder='Select Options',     
                    clearable=True,                     
                    style={'width':"100%"})
        ])
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Hr(style={'height': '10px', 'color': 'blue'})
        ])
    ]),
    
#  ----------------------------------------------------------------------------------------------------------
    
    dbc.Row([
        dbc.Col([
            html.H1("Salary VS Number of Employees")
        ], width=6)
    ]),
    
    dbc.Row([
        dbc.Col([
            dcc.Graph(id='Graph3', figure=barchart1)
        ], width=12)
    ]),
    
    dbc.Row([
        dbc.Col([
            html.Hr(style={'height': '10px', 'color': 'blue'})
        ])
    ])
])
, style={'backgroundColor':'#f8e9fb'})

In [7]:
@app.callback(
    Output(component_id='output_container1', component_property='children'),
    Output(component_id='output_container2', component_property='children'),
    Output(component_id='output_container3', component_property='children'),
    Output(component_id='output_container4', component_property='children'),
    [Input('no_of_emp','value'),
    Input('Positions','value')]
)

def calculator_output(no_of_emp,Position):
    data = df1.copy()
    data = data[data['Position']==Position]
    x1=data['Salary/month/employee']
    x2=data['Salary/year/employee'] 
    s_per_emp = round(x1, 2)
    s_emp = round(x1*no_of_emp, 2)
    s_per_year = round(x2, 2)
    s_year = round(x2*no_of_emp, 2)
    
    return s_per_emp, s_emp, s_per_year, s_year

# ----------------------------------------------------------------------------------------------------------------

@app.callback(
    Output(component_id='Graph1', component_property='figure'),
    [Input(component_id='Department', component_property='value')]
)

def graphs(Department):
    df = pd.read_excel(f"{Department}.xlsx")
    piechart = px.pie(
        data_frame=df,
        values='Salary/month/employee',
        names='Position',
        color='Position',                      
        
        hover_name='Salary/month',                     
        title=Department+" Table",
        template='plotly_white',
        hole=0.1
        )
    piechart.update_traces(textinfo='value+label', opacity=1, rotation=150)
    
    return piechart

# ----------------------------------------------------------------------------------------------------------------

@app.callback(
    Output(component_id='Graph2', component_property='figure'),
    [Input(component_id='yaxis_raditem', component_property='value')]
)

def update_graph(y_axis):
    dff = df
    barchart=px.bar(
            data_frame=dff,
            x="Position",
            y=y_axis,
            title=y_axis+': By Position',
            color="Position",
            barmode="group",
            template='plotly_white',
            )
    barchart.update_layout(xaxis={'categoryorder':'total descending'},
                           title={'xanchor':'center', 'yanchor': 'top', 'y':0.9,'x':0.5,})
    
    
    return barchart

In [ ]:
if __name__ == '__main__':
    app.run_server(port=8050)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET /_favicon.ico?v=2.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:34] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:35] "POST /_dash-update-component HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_9396\3497428622.py", line 16, in calculator_output
    s_emp = round(x1*no_of_emp, 2)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 70, in new_method
    return method(self, other)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 128, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

127.0.0.1 - - [03/Dec/2022 10:58:35] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2022 10:58:35] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 10:58:36] "GET /_favicon.ico?v=2.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:45] "POST /_dash-update-component HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_9396\3497428622.py", line 16, in calculator_output
    s_emp = round(x1*no_of_emp, 2)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 70, in new_method
    return method(self, other)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 128, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

127.0.0.1 - - [03/Dec/2022 11:00:47] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2022 11:00:48] "POST /_dash-update-component HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_9396\3497428622.py", line 16, in calculator_output
    s_emp = round(x1*no_of_emp, 2)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 70, in new_method
    return method(self, other)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 128, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

127.0.0.1 - - [03/Dec/2022 11:00:50] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2022 11:00:51] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "GET /_favicon.ico?v=2.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_9396\3497428622.py", line 16, in calculator_output
    s_emp = round(x1*no_of_emp, 2)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 70, in new_method
    return method(self, other)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 128, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

127.0.0.1 - - [03/Dec/2022 11:00:53] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:53] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:54] "GET /_favicon.ico?v=2.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:55] "POST /_dash-update-component HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_9396\3497428622.py", line 16, in calculator_output
    s_emp = round(x1*no_of_emp, 2)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 70, in new_method
    return method(self, other)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 128, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

127.0.0.1 - - [03/Dec/2022 11:00:57] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2022 11:00:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_favicon.ico?v=2.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\HP\anaconda3\lib\site-packages\dash\_callback.py", line 440, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "C:\Users\HP\AppData\Local\Temp\ipykernel_9396\3497428622.py", line 16, in calculator_output
    s_emp = round(x1*no_of_emp, 2)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\common.py", line 70, in new_method
    return method(self, other)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\ops\array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 128, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "C:\Users\HP\anaconda3\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

127.0.0.1 - - [03/Dec/2022 11:00:59] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:00:59] "GET /_favicon.ico?v=2.7.0 HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:01:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:38] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:38] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:39] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:40] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:41] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:41] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:41] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:42] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:42] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:42] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:42] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:42] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:43] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:43] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:43] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:43] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:43] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:44] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [03/Dec/2022 11:24:47] "POST /_dash-update-component HTTP/1.1" 200 -